name: Append PR author to GSheet
on:
  pull_request:
    types:
      - closed

jobs:
  append-to-gsheet:
    runs-on: ubuntu-latest

    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v2.1.1
        with:
          spreadsheetId: 113L7a7fyUnMmdihUakCEaAxTRuYesUUp6s7ISEyslCk
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "DTP Exercise 2" }},
              { "command": "appendData", "args": { "data": [["${{ github.repository_owner }}", "${{ github.event.pull_request.user.login }}"]], "minCol": 1 }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}